ALTER TABLE user_detail ADD COLUMN PROFILE_PIC_PATH VARCHAR(300) NULL AFTER PHOTO_PASSPORT_SIZE

--26th Oct 2020
ALTER TABLE josthi_db.user_detail ADD COLUMN GENDER VARCHAR(10) NULL AFTER LAST_NAME;
ALTER TABLE josthi_db.user_detail ADD COLUMN ZIP_PIN VARCHAR(20) NULL AFTER COUNTRY;
ALTER TABLE josthi_db.user_detail ADD COLUMN LAND_LINE_NO VARCHAR(20) NULL AFTER WHATSAPP_NO;
ALTER TABLE josthi_db.user_detail ADD COLUMN FAX_NO VARCHAR(20) NULL AFTER LAND_LINE_NO;
ALTER TABLE josthi_db.user_detail ADD COLUMN OFFICE_PH_NO VARCHAR(20) NULL AFTER FAX_NO;


ALTER TABLE josthi_db.user_detail ADD COLUMN ADDITIONAL_ADDRESS_LINE VARCHAR(100) NULL AFTER USER_ADDRESS_SECOND_LINE
ALTER TABLE josthi_db.user_detail ADD COLUMN POLICE_STATION VARCHAR(50) NULL AFTER ADDITIONAL_ADDRESS_LINE
ALTER TABLE josthi_db.user_detail ADD COLUMN POST_OFFICE VARCHAR(50) NULL AFTER POLICE_STATION
ALTER TABLE josthi_db.user_detail ADD COLUMN NEAREST_LAND_MARK VARCHAR(100) NULL AFTER POST_OFFICE
ALTER TABLE josthi_db.user_detail ADD COLUMN COVERAGE_AREA VARCHAR(50) NULL AFTER NEAREST_LAND_MARK

ALTER TABLE josthi_db.user_detail ADD COLUMN AGENCY_NAME VARCHAR(100) NULL AFTER COMMENTS
ALTER TABLE josthi_db.user_detail ADD COLUMN AGENCY_DESCRIPTION VARCHAR(300) NULL AFTER AGENCY_NAME

ALTER TABLE josthi_db.user_auth_table ADD COLUMN ENABLED tinyint NOT NULL DEFAULT '1' AFTER TEMPORARY_LOCK_ENABLED;
ALTER TABLE josthi_db.user_auth_table ADD COLUMN VERIFIED_USER VARCHAR(2) NOT NULL DEFAULT 'N' AFTER `ENABLED`;


CREATE TABLE josthi_db.agent_enquery (
  ENQUERY_ID INT NOT NULL AUTO_INCREMENT,
  EMAIL_ID VARCHAR(60) NOT NULL,
  AGENT_NAME VARCHAR(110) NOT NULL,
  AGENT_QUERY VARCHAR(400) NULL,
  AGENT_QUERY_TYPE VARCHAR(100) NULL,
  REQUEST_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  QUERY_RESOLVED_ON DATETIME NULL,
  ENQUERY_STATUS VARCHAR(10) NOT NULL DEFAULT 'OPEN',
  AGENT_CONTACT_NO VARCHAR(20) NULL,
  AGENT_COVERAGE_AREA VARCHAR(10) NULL,
  PRIMARY KEY (ENQUERY_ID));

  -- *************************** Installed on Nov 11 2020 ********************************
  CREATE TABLE emergency_contact_details (
  CONTACT_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY_UID VARCHAR(15) NOT NULL,
  BEN_ID VARCHAR(15) NULL,
  EMERGENCY_CONTACT_NAME VARCHAR(100) NULL,
  EMERGENCY_CONTACT_NUMBER VARCHAR(20) NOT NULL,
  EMERGENCY_CONTACT_STAY_LOCATION VARCHAR(100) NULL,
  RELATION VARCHAR(50) NULL,
  CONTACT_NO_VALIDATED VARCHAR(5) NULL DEFAULT 'NO',
  INSERT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NOTES VARCHAR(1000) NULL,
  PRIMARY KEY (CONTACT_ID),
  UNIQUE INDEX INSERT_DATE_UNIQUE (INSERT_DATE ASC));
  
  
  CREATE TABLE relation (
  RELATION_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID VARCHAR(15) NOT NULL,
  BENEFICIARY_ID VARCHAR(15) NULL,
  AGENT_ID VARCHAR(15) NULL,
  BENEFICIARY_TYPE VARCHAR(20) NULL,
  INSERT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (RELATION_ID));
  
  
  CREATE TABLE beneficiary_detail (
  tid INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID VARCHAR(15) NULL,
  BENEFICIARY_ID VARCHAR(15) NOT NULL,
  RELATION_WITH_CUSTOMER VARCHAR(45) NULL,
  DATE_OF_BIRTH DATETIME NULL,
  AGE VARCHAR(20) NULL,
  HEIGHT VARCHAR(20) NULL,
  WEIGHT VARCHAR(20) NULL,
  BLOOD_GROUP VARCHAR(20) NULL,
  PREFFERED_HOSPITAL VARCHAR(200) NULL,
  MEDICLAME_NAME VARCHAR(200) NULL,
  INSURANCE_NOTE VARCHAR(200) NULL,
  HEALTH_CONDITION VARCHAR(1000) NULL,
  MEDICAL_CHALLENGES VARCHAR(500) NULL,
  PRIMARY KEY (tid));
  
  CREATE TABLE dropdown_metadata (
  TID int NOT NULL AUTO_INCREMENT,
  DROPDOWN_TYPE varchar(100) NOT NULL,
  KEY_ID varchar(300) NOT NULL,
  DROPDOWN_VALUE varchar(300) NOT NULL,
  ACTIVE varchar(1) NOT NULL DEFAULT 'Y',
  UPDATE_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TID)
)

INSERT INTO dropdown_metadata (DROPDOWN_TYPE,KEY_ID,DROPDOWN_VALUE,ACTIVE) VALUES 
('BLOOD_GROUP','O-','O-','Y')
,('BLOOD_GROUP','O+','O+','Y')
,('BLOOD_GROUP','A-','A-','Y')
,('BLOOD_GROUP','A+','A+','Y')
,('BLOOD_GROUP','B-','B-','Y')
,('BLOOD_GROUP','B+','B+','Y')
,('BLOOD_GROUP','AB-','AB-','Y')
,('BLOOD_GROUP','AB+','AB+','Y')
,('BLOOD_GROUP','Others','Others','Y')
,('BLOOD_GROUP','No Idea','No Idea','Y');

--****************************************************************************************
--************************ NEXT RELEASE **************************************************

ALTER TABLE `josthi_db`.`user_auth_table` 
ADD COLUMN `OTP` VARCHAR(45) NULL AFTER `VERIFIED_USER`,
ADD COLUMN `VALID_EMAIL` VARCHAR(10) NOT NULL DEFAULT 'NO' AFTER `OTP`
  
  
  
  
  
