ALTER TABLE user_detail ADD COLUMN PROFILE_PIC_PATH VARCHAR(300) NULL AFTER PHOTO_PASSPORT_SIZE

--26th Oct 2020
ALTER TABLE josthi_db.user_detail ADD COLUMN GENDER VARCHAR(10) NULL AFTER LAST_NAME;
ALTER TABLE josthi_db.user_detail ADD COLUMN ZIP_PIN VARCHAR(20) NULL AFTER COUNTRY;
ALTER TABLE josthi_db.user_detail ADD COLUMN LAND_LINE_NO VARCHAR(20) NULL AFTER WHATSAPP_NO;
ALTER TABLE josthi_db.user_detail ADD COLUMN FAX_NO VARCHAR(20) NULL AFTER LAND_LINE_NO;
ALTER TABLE josthi_db.user_detail ADD COLUMN OFFICE_PH_NO VARCHAR(20) NULL AFTER FAX_NO;


ALTER TABLE josthi_db.user_detail ADD COLUMN ADDITIONAL_ADDRESS_LINE VARCHAR(100) NULL AFTER USER_ADDRESS_SECOND_LINE
ALTER TABLE josthi_db.user_detail ADD COLUMN POLICE_STATION VARCHAR(50) NULL AFTER ADDITIONAL_ADDRESS_LINE
ALTER TABLE josthi_db.user_detail ADD COLUMN POST_OFFICE VARCHAR(50) NULL AFTER POLICE_STATION
ALTER TABLE josthi_db.user_detail ADD COLUMN NEAREST_LAND_MARK VARCHAR(100) NULL AFTER POST_OFFICE
ALTER TABLE josthi_db.user_detail ADD COLUMN COVERAGE_AREA VARCHAR(50) NULL AFTER NEAREST_LAND_MARK

ALTER TABLE josthi_db.user_detail ADD COLUMN AGENCY_NAME VARCHAR(100) NULL AFTER COMMENTS
ALTER TABLE josthi_db.user_detail ADD COLUMN AGENCY_DESCRIPTION VARCHAR(300) NULL AFTER AGENCY_NAME

ALTER TABLE josthi_db.user_auth_table ADD COLUMN ENABLED tinyint NOT NULL DEFAULT '1' AFTER TEMPORARY_LOCK_ENABLED;
ALTER TABLE josthi_db.user_auth_table ADD COLUMN VERIFIED_USER VARCHAR(2) NOT NULL DEFAULT 'N' AFTER `ENABLED`;


CREATE TABLE josthi_db.agent_enquery (
  ENQUERY_ID INT NOT NULL AUTO_INCREMENT,
  EMAIL_ID VARCHAR(60) NOT NULL,
  AGENT_NAME VARCHAR(110) NOT NULL,
  AGENT_QUERY VARCHAR(400) NULL,
  AGENT_QUERY_TYPE VARCHAR(100) NULL,
  REQUEST_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  QUERY_RESOLVED_ON DATETIME NULL,
  ENQUERY_STATUS VARCHAR(10) NOT NULL DEFAULT 'OPEN',
  AGENT_CONTACT_NO VARCHAR(20) NULL,
  AGENT_COVERAGE_AREA VARCHAR(10) NULL,
  PRIMARY KEY (ENQUERY_ID));

  -- *************************** Next Install ********************************
  CREATE TABLE josthi_db.emergency_contact_details (
  CONTACT_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY_UID VARCHAR(15) NOT NULL,
  BEN_ID VARCHAR(15) NULL,
  EMERGENCY_CONTACT_NAME VARCHAR(100) NULL,
  EMERGENCY_CONTACT_NUMBER VARCHAR(20) NOT NULL,
  EMERGENCY_CONTACT_STAY_LOCATION VARCHAR(100) NOT NULL,
  RELATION VARCHAR(50) NULL,
  CONTACT_NO_VALIDATED VARCHAR(5) NULL DEFAULT 'NO',
  INSERT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NOTES VARCHAR(1000) NULL,
  PRIMARY KEY (`CONTACT_ID`),
  UNIQUE INDEX `INSERT_DATE_UNIQUE` (`INSERT_DATE` ASC) VISIBLE);
  
  
